### ISSUE TITLE
Hey Joey

### ISSUE THREAD

**Issue by reteps** [JoeyBrar/JoeyBrar.github.io#1]
Hey Joey,

I am still "watching" this repository on github, and saw you were having an issue with your website.

Github needs your username and repository name to match up. This means that your Repository name needs to be `JoeyBrar.github.io` instead of `Sn0wyJoey.github.io`. Change that on github, then the website https://JoeyBrar.github.io should work

**Comment by JoeyBrar** [comment]
Ok, thanks!
